// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: protos/work/work.proto

package work

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkTask int32

const (
	WorkTask_WORK_TASK_UNSPECIFIED WorkTask = 0
	WorkTask_WORK_TASK_DANCE       WorkTask = 1
	WorkTask_WORK_TASK_PLAY        WorkTask = 2
)

// Enum value maps for WorkTask.
var (
	WorkTask_name = map[int32]string{
		0: "WORK_TASK_UNSPECIFIED",
		1: "WORK_TASK_DANCE",
		2: "WORK_TASK_PLAY",
	}
	WorkTask_value = map[string]int32{
		"WORK_TASK_UNSPECIFIED": 0,
		"WORK_TASK_DANCE":       1,
		"WORK_TASK_PLAY":        2,
	}
)

func (x WorkTask) Enum() *WorkTask {
	p := new(WorkTask)
	*p = x
	return p
}

func (x WorkTask) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkTask) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_work_work_proto_enumTypes[0].Descriptor()
}

func (WorkTask) Type() protoreflect.EnumType {
	return &file_protos_work_work_proto_enumTypes[0]
}

func (x WorkTask) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkTask.Descriptor instead.
func (WorkTask) EnumDescriptor() ([]byte, []int) {
	return file_protos_work_work_proto_rawDescGZIP(), []int{0}
}

type WorkStatus int32

const (
	WorkStatus_WORK_STATUS_UNSPECIFIED WorkStatus = 0
	WorkStatus_WORK_STATUS_SUCCESS     WorkStatus = 1
	WorkStatus_WORK_STATUS_FAILED      WorkStatus = 2
	WorkStatus_WORK_STATUS_STARTED     WorkStatus = 3
	WorkStatus_WORK_STATUS_IN_PROGRESS WorkStatus = 4
)

// Enum value maps for WorkStatus.
var (
	WorkStatus_name = map[int32]string{
		0: "WORK_STATUS_UNSPECIFIED",
		1: "WORK_STATUS_SUCCESS",
		2: "WORK_STATUS_FAILED",
		3: "WORK_STATUS_STARTED",
		4: "WORK_STATUS_IN_PROGRESS",
	}
	WorkStatus_value = map[string]int32{
		"WORK_STATUS_UNSPECIFIED": 0,
		"WORK_STATUS_SUCCESS":     1,
		"WORK_STATUS_FAILED":      2,
		"WORK_STATUS_STARTED":     3,
		"WORK_STATUS_IN_PROGRESS": 4,
	}
)

func (x WorkStatus) Enum() *WorkStatus {
	p := new(WorkStatus)
	*p = x
	return p
}

func (x WorkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_work_work_proto_enumTypes[1].Descriptor()
}

func (WorkStatus) Type() protoreflect.EnumType {
	return &file_protos_work_work_proto_enumTypes[1]
}

func (x WorkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkStatus.Descriptor instead.
func (WorkStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_work_work_proto_rawDescGZIP(), []int{1}
}

type StartWorkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Task WorkTask `protobuf:"varint,2,opt,name=task,proto3,enum=work.WorkTask" json:"task,omitempty"`
}

func (x *StartWorkRequest) Reset() {
	*x = StartWorkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_work_work_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkRequest) ProtoMessage() {}

func (x *StartWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_work_work_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkRequest.ProtoReflect.Descriptor instead.
func (*StartWorkRequest) Descriptor() ([]byte, []int) {
	return file_protos_work_work_proto_rawDescGZIP(), []int{0}
}

func (x *StartWorkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartWorkRequest) GetTask() WorkTask {
	if x != nil {
		return x.Task
	}
	return WorkTask_WORK_TASK_UNSPECIFIED
}

type StartWorkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkId string `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
}

func (x *StartWorkResponse) Reset() {
	*x = StartWorkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_work_work_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkResponse) ProtoMessage() {}

func (x *StartWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_work_work_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkResponse.ProtoReflect.Descriptor instead.
func (*StartWorkResponse) Descriptor() ([]byte, []int) {
	return file_protos_work_work_proto_rawDescGZIP(), []int{1}
}

func (x *StartWorkResponse) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriberId string `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_work_work_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_work_work_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_protos_work_work_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

type WorkStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkId string     `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Status WorkStatus `protobuf:"varint,2,opt,name=status,proto3,enum=work.WorkStatus" json:"status,omitempty"`
}

func (x *WorkStatusResponse) Reset() {
	*x = WorkStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_work_work_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkStatusResponse) ProtoMessage() {}

func (x *WorkStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_work_work_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkStatusResponse.ProtoReflect.Descriptor instead.
func (*WorkStatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_work_work_proto_rawDescGZIP(), []int{3}
}

func (x *WorkStatusResponse) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *WorkStatusResponse) GetStatus() WorkStatus {
	if x != nil {
		return x.Status
	}
	return WorkStatus_WORK_STATUS_UNSPECIFIED
}

var File_protos_work_work_proto protoreflect.FileDescriptor

var file_protos_work_work_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x4a,
	0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x2c, 0x0a, 0x11, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x57, 0x0a, 0x12, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64,
	0x12, 0x28, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x4e, 0x0a, 0x08, 0x57, 0x6f,
	0x72, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x19, 0x0a, 0x15, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x54,
	0x41, 0x53, 0x4b, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x44,
	0x41, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x54,
	0x41, 0x53, 0x4b, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x10, 0x02, 0x2a, 0x90, 0x01, 0x0a, 0x0a, 0x57,
	0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17, 0x57, 0x4f, 0x52,
	0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12,
	0x16, 0x0a, 0x12, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46,
	0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x57, 0x4f, 0x52, 0x4b, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x03,
	0x12, 0x1b, 0x0a, 0x17, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x04, 0x32, 0x9f, 0x01,
	0x0a, 0x04, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x3e, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x57,
	0x6f, 0x72, 0x6b, 0x12, 0x16, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x1f, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x54, 0x6f, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x6f, 0x62, 0x69, 0x6e, 0x57,
	0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f,
	0x6c, 0x61, 0x6e, 0x64, 0x73, 0x65, 0x69, 0x67, 0x6c, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_work_work_proto_rawDescOnce sync.Once
	file_protos_work_work_proto_rawDescData = file_protos_work_work_proto_rawDesc
)

func file_protos_work_work_proto_rawDescGZIP() []byte {
	file_protos_work_work_proto_rawDescOnce.Do(func() {
		file_protos_work_work_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_work_work_proto_rawDescData)
	})
	return file_protos_work_work_proto_rawDescData
}

var file_protos_work_work_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_work_work_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_work_work_proto_goTypes = []interface{}{
	(WorkTask)(0),              // 0: work.WorkTask
	(WorkStatus)(0),            // 1: work.WorkStatus
	(*StartWorkRequest)(nil),   // 2: work.StartWorkRequest
	(*StartWorkResponse)(nil),  // 3: work.StartWorkResponse
	(*SubscribeRequest)(nil),   // 4: work.SubscribeRequest
	(*WorkStatusResponse)(nil), // 5: work.WorkStatusResponse
}
var file_protos_work_work_proto_depIdxs = []int32{
	0, // 0: work.StartWorkRequest.task:type_name -> work.WorkTask
	1, // 1: work.WorkStatusResponse.status:type_name -> work.WorkStatus
	2, // 2: work.Work.StartWork:input_type -> work.StartWorkRequest
	4, // 3: work.Work.SubscribeToRoundRobinWorkStatus:input_type -> work.SubscribeRequest
	3, // 4: work.Work.StartWork:output_type -> work.StartWorkResponse
	5, // 5: work.Work.SubscribeToRoundRobinWorkStatus:output_type -> work.WorkStatusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_work_work_proto_init() }
func file_protos_work_work_proto_init() {
	if File_protos_work_work_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_work_work_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartWorkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_work_work_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartWorkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_work_work_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_work_work_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_work_work_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_work_work_proto_goTypes,
		DependencyIndexes: file_protos_work_work_proto_depIdxs,
		EnumInfos:         file_protos_work_work_proto_enumTypes,
		MessageInfos:      file_protos_work_work_proto_msgTypes,
	}.Build()
	File_protos_work_work_proto = out.File
	file_protos_work_work_proto_rawDesc = nil
	file_protos_work_work_proto_goTypes = nil
	file_protos_work_work_proto_depIdxs = nil
}
